### ISSUE TITLE
鼠标点击的特效怎么去掉

### ISSUE THREAD

**Issue by zhaoch93** [Neveryu/Neveryu.github.io#3]
rt

**Comment by Neveryu** [comment]
在这篇文章[Hexo-NexT搭建个人博客（二）](https://neveryu.github.io/2016/09/30/hexo-next-two/)中写到了：
![two-xiaohongxin](https://user-images.githubusercontent.com/14313328/28500402-4c89b382-6ffa-11e7-8319-eb7fb250dd55.png)
去掉这一段代码，就可以去掉点击的特效了。
